# Generated by Django 4.2.13 on 2024-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='custom_distance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='custom_distance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
