# Generated by Django 4.2.13 on 2024-07-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='team',
        ),
        migrations.AddField(
            model_name='registration',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RelayEntry.teammember'),
        ),
    ]
