# Generated by Django 4.2.14 on 2024-07-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='photopackage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='race',
            name='created_by',
        ),
    ]
