# Generated by Django 4.2.13 on 2024-06-01 19:07

from django.db import migrations, models

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('RelayEntry', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]