# Generated by Django 4.2.13 on 2024-06-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='Only if the event spans multiple days. Must be after the date field.', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(default='2000-01-01 00:00:00', help_text='The time the race starts.'),
        ),
        migrations.AlterField(
            model_name='photopackage',
            name='event',
            field=models.ForeignKey(help_text='Which event the photo package is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='photo_packages', to='RelayEntry.event'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(help_text='The event you created that this race belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='races', to='RelayEntry.event'),
        ),
        migrations.AlterField(
            model_name='race',
            name='is_relay',
            field=models.BooleanField(default=False, help_text='Is the race a team relay race?'),
        ),
    ]
