# Generated by Django 4.2.13 on 2024-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_default_waiver_text(apps, schema_editor):
        Event = apps.get_model('RelayEntry', 'Event')
        default_text = "Default waiver text"
        for event in Event.objects.all():
            event.waiver_text = default_text
            event.save()

    dependencies = [
        ('RelayEntry', '0002_alter_leg_custom_distance_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='waivers',
        ),
        migrations.RemoveField(
            model_name='race',
            name='waiver_text',
        ),
        migrations.AddField(
            model_name='event',
            name='waiver_text',
            field=models.TextField(default="Temporary default text"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='waiver_text',
            field=models.TextField(default="Temporary default text"),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_waiver_text),
        migrations.AlterField(
            model_name='event',
            name='waiver_text',
            field=models.TextField(),  # Remove default to restore original state
        ),
        migrations.AlterField(
            model_name='registration',
            name='waiver_text',
            field=models.TextField(),  # Remove default to restore original state
        ),
        migrations.DeleteModel(
            name='Waiver',
        ),
    ]
