# Generated by Django 4.2.13 on 2024-06-01 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0002_auto_20240601_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='document',
            name='required',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='percentage',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='custom_distance_unit',
            field=models.CharField(blank=True, choices=[('mi', 'Miles'), ('km', 'Kilometers'), ('m', 'Meters')], max_length=2, null=True),
        ),
    ]
