# Generated by Django 4.2.13 on 2024-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0002_event_end_date_race_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(help_text='The time the race starts.'),
        ),
    ]
