# Generated by Django 4.2.13 on 2024-07-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0002_remove_registration_team_registration_team_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='team_member',
            new_name='member',
        ),
    ]
