# Generated by Django 4.2.13 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0003_rename_team_member_registration_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
