# Generated by Django 4.2.13 on 2024-06-01 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0003_remove_couponcode_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
