# Generated by Django 4.2.14 on 2024-07-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0003_remove_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='race',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='RelayEntry.race'),
            preserve_default=False,
        ),
    ]
