# Generated by Django 4.2.13 on 2024-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0003_alter_race_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
