# Generated by Django 4.2.13 on 2024-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0003_remove_event_waivers_remove_race_waiver_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='minor',
            field=models.BooleanField(default=False, help_text='Parent/Guardian for Minors (Under 18 years old)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default=None, help_text='Name of the participant', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='parent_guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='parent_guardian_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
