# Generated by Django 4.2.13 on 2024-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0004_registration_minor_registration_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default=None, help_text='First name of the participant', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default=None, help_text='Last name of the participant', max_length=255),
            preserve_default=False,
        ),
    ]
