# Generated by Django 4.2.13 on 2024-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0004_userprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
