# Generated by Django 4.2.13 on 2024-06-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0004_alter_couponcode_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='same_distance',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveIntegerField()),
                ('custom_distance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_distance_unit', models.CharField(blank=True, choices=[('mi', 'Miles'), ('km', 'Kilometers'), ('m', 'Meters')], max_length=2, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='RelayEntry.race')),
            ],
            options={
                'unique_together': {('race', 'leg_number')},
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='leg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teammember', to='RelayEntry.leg'),
        ),
    ]
