# Generated by Django 4.2.13 on 2024-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0005_event_description_race_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The price of registration before a discount may or may not have been applied.', max_digits=10),
        ),
    ]
