# Generated by Django 4.2.13 on 2024-06-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0006_registration_gender_registration_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='email_url',
            new_name='email',
        ),
        migrations.AddField(
            model_name='team',
            name='projected_team_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
