# Generated by Django 4.2.13 on 2024-06-09 18:54

from django.db import migrations, models
# import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0006_race_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='waivers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('required', models.BooleanField(default=False, help_text='Is this waiver required for registration?')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='google_map_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='url_alias',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='leg_map',
            field=models.FileField(blank=True, null=True, upload_to='leg_maps/'),
        ),
        migrations.AddField(
            model_name='race',
            name='course_map',
            field=models.FileField(blank=True, null=True, upload_to='race_course_maps/'),
        ),
        # migrations.AddField(
        #     model_name='race',
        #     name='timezone',
        #     field=timezone_field.fields.TimeZoneField(default='UTC'),
        # ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(help_text='The time the race starts per the timezone you select!'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='event',
            name='waivers',
            field=models.ManyToManyField(blank=True, help_text='Waivers for registration.', related_name='events', to='RelayEntry.waiver'),
        ),
    ]
