# Generated by Django 4.2.13 on 2024-06-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0007_waiver_event_google_map_html_event_url_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_map_html',
            field=models.TextField(blank=True, help_text="Embed HTML for the Google Maps location. You can get this from the 'Embed a map' section of the Google Maps share options.", null=True),
        ),
    ]
