# Generated by Django 4.2.15 on 2024-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0007_result_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='registration_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='bib_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='bib_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('VIP', 'VIP'), ('Elite', 'Elite')], default='Standard', max_length=50),
        ),
    ]
