# Generated by Django 4.2.13 on 2024-06-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0008_alter_event_google_map_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='google_map_html',
            new_name='google_maps_html',
        ),
    ]
