# Generated by Django 4.2.15 on 2024-08-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0008_race_registration_closed_registration_bib_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False),
        ),
    ]
