# Generated by Django 4.2.13 on 2024-06-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0008_alter_event_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='same_distance',
            field=models.BooleanField(default=False, help_text='Whether each leg of the team relay race is the same distance.'),
        ),
    ]
