# Generated by Django 4.2.13 on 2024-06-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0009_alter_race_same_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='custom_distance_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If each leg is the same distance, put that distance here. Otherwise put the total distance (if legs differ in distance.)', max_digits=7, null=True),
        ),
    ]
