# Generated by Django 4.2.13 on 2024-06-09 20:04

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0009_rename_google_map_html_event_google_maps_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices=[('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'), ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Anchorage', 'America/Anchorage'), ('America/Phoenix', 'America/Phoenix'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('Pacific/Honolulu', 'Pacific/Honolulu'), ('America/Detroit', 'America/Detroit'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Menominee', 'America/Menominee'), ('America/North_Dakota/Center', 'America/North_Dakota/Center'), ('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem'), ('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah')], default='UTC'),
        ),
    ]
