# Generated by Django 4.2.15 on 2024-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0009_event_registration_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
