# Generated by Django 4.2.13 on 2024-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0010_alter_race_custom_distance_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
