# Generated by Django 4.2.13 on 2024-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0010_alter_race_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(help_text='The time the race starts'),
        ),
    ]
