# Generated by Django 4.2.16 on 2024-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0010_registration_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
