# Generated by Django 4.2.16 on 2024-09-08 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0011_alter_registration_email_alter_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='female_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='race_tshirts/'),
        ),
        migrations.AddField(
            model_name='event',
            name='male_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='race_tshirts/'),
        ),
        migrations.AddField(
            model_name='race',
            name='female_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_tshirts/'),
        ),
        migrations.AddField(
            model_name='race',
            name='male_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_tshirts/'),
        ),
        migrations.AddField(
            model_name='race',
            name='projected_time_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency Contact Full Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='has_medical_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='medical_condition_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='projected_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL'), ('XXXL', 'Triple XL')], max_length=4, null=True),
        ),
    ]
