# Generated by Django 4.2.13 on 2024-06-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0011_teammember_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='leg',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
        migrations.AddField(
            model_name='team',
            name='emails',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='leg_order',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RelayEntry.registration'),
        ),
    ]
