# Generated by Django 4.2.13 on 2024-06-24 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0012_remove_teammember_dob_remove_teammember_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='projected_team_time_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
