# Generated by Django 5.0.4 on 2024-09-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0012_event_female_tshirt_image_event_male_tshirt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='RelayEntry.userprofile'),
        ),
    ]
