# Generated by Django 4.2.13 on 2024-06-24 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0013_team_projected_team_time_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='projected_team_time_choices',
        ),
        migrations.AddField(
            model_name='race',
            name='projected_team_time_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='registration',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
