# Generated by Django 5.0.4 on 2024-10-05 20:25

import RelayEntry.utils.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0013_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='female_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='race_tshirts/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='The event page image', null=True, upload_to='event_logos/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='male_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='race_tshirts/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='event_media/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='leg_map',
            field=models.FileField(blank=True, null=True, upload_to='leg_maps/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='race',
            name='course_map',
            field=models.FileField(blank=True, null=True, upload_to='race_course_maps/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='race',
            name='female_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_tshirts/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='race',
            name='male_tshirt_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_tshirts/', validators=[RelayEntry.utils.models_utils.validate_file_size]),
        ),
    ]
