# Generated by Django 4.2.13 on 2024-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0014_remove_race_signed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leg_order',
        ),
        migrations.AlterField(
            model_name='team',
            name='emails',
            field=models.JSONField(default=list, help_text='Includes leg order'),
        ),
    ]
