# Generated by Django 5.0.4 on 2024-10-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0015_race_address_race_city_race_postal_code_race_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='projected_team_time',
            new_name='projected_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='projected_team_time_choices',
        ),
    ]
