# Generated by Django 4.2.13 on 2024-06-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0015_remove_team_leg_order_alter_team_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='RelayEntry.registration'),
        ),
    ]
