# Generated by Django 4.2.13 on 2024-06-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0016_alter_team_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='registration',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='leg',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
