# Generated by Django 4.2.13 on 2024-06-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0017_remove_teammember_email_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='emails',
        ),
    ]
