# Generated by Django 4.2.13 on 2024-06-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0018_remove_team_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='leg',
            new_name='leg_order',
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='RelayEntry.team'),
            preserve_default=False,
        ),
    ]
