# Generated by Django 4.2.13 on 2024-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelayEntry', '0019_rename_leg_teammember_leg_order_teammember_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='registration',
        ),
    ]
