# Generated by Django 4.2.13 on 2024-05-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_race_custom_distance_unit_race_custom_distance_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='num_runners',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='team_type',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed'), ('Coed', 'Coed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='backend.registration')),
            ],
        ),
        migrations.CreateModel(
            name='RacePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_date', models.DateField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.race')),
            ],
            options={
                'unique_together': {('race', 'effective_date')},
            },
        ),
    ]
