# Generated by Django 4.2.13 on 2024-05-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_couponcode_photopackage_event_email_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmation_code',
            field=models.CharField(default=None, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
