# Generated by Django 4.2.13 on 2024-05-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_registration_confirmation_code_registration_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name', 'event__name']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.RenameField(
            model_name='couponcode',
            old_name='valid_from',
            new_name='valid_until',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='logo_or_branch_photo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='documents',
            new_name='waivers',
        ),
        migrations.RemoveField(
            model_name='couponcode',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='race_price',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='teammember',
            name='leg_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photopackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RacePrice',
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='backend.teammember'),
        ),
        migrations.AddField(
            model_name='team',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='backend.race'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
    ]
