# Use the official Node.js image from the Docker Hub
FROM node:18-alpine

# Set work directory
WORKDIR /app

# Copy package.json and package-lock.json (if using npm)
COPY package*.json ./

RUN npm install
COPY . .

# Expose the port that the app runs on
EXPOSE 8080

# Run the application
CMD ["npm", "run", "serve"]
