version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80" # Use expose instead of ports for internal communicatio
    depends_on:
      - backend
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/logs:/app/logs
    expose:
      - "8000" # Use expose instead of ports for internal communication
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always
volumes:
  pgdata:
