version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production 
    volumes:
      - staticfiles:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt  # Map the SSL certificates
    ports:
      - "80:80" # Use expose instead of ports for internal communication
      - "443:443"
    depends_on:
      - backend
    restart: always
    env_file:
      - .env.frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/logs:/app/logs
      - staticfiles:/app/staticfiles
    expose:
      - "8000" # Use expose instead of ports for internal communication
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  staticfiles:
