version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt  # Map the SSL certificates
    ports:
      - "80:80" # Use expose instead of ports for internal communication
      - "443:443"
    depends_on:
      - backend
    restart: always
    env_file:
       - ./frontend/.env.production
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/logs:/app/logs
      - staticfiles:/app/staticfiles
      - media:/app/media
    expose:
      - "8000" # Use expose instead of ports for internal communication
    env_file:
      - ./backend/.env.backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
    restart: always
volumes:
  staticfiles:
  media:
  logs:
