version: '3.8'
services:
  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mailhog
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    restart: always
    environment:
      - NODE_ENV=development  # This sets the environment to development mode
    env_file:
      - .env.frontend  # Use the frontend-specific environment file
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  pgdata: {}