version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=relaydb
      - POSTGRES_USER=relayuser
      - POSTGRES_PASSWORD=relaypassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
    depends_on:
      - postgres
      - mailhog
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=relaydb
      - POSTGRES_USER=relayuser
      - POSTGRES_PASSWORD=relaypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  pgdata: {}
