# Generated by Django 4.2.13 on 2024-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='custom_distance_unit',
            field=models.CharField(blank=True, choices=[('mi', 'Miles'), ('km', 'Kilometers')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='custom_distance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='is_relay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(choices=[('5K', '5K'), ('10K', '10K'), ('Half Marathon', 'Half Marathon'), ('Marathon', 'Marathon'), ('Ultra Marathon', 'Ultra Marathon'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
